on: [push]
jobs:
  build:
    name: Sync with server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Write a multi-line message
      run: |
        curl https://admin.thatrandompi.xyz/sites/thatrandompi_xyz/sync
